### ISSUE TITLE
Uncaught No class name passed!

### ISSUE THREAD

**Issue by tortuetorche** [tocjent/php-integrator-symbol-viewer#11]
![Screenshot](http://i.stack.imgur.com/uNZGW.png)

This is how @teresko get to it:

1. file > add project folder
2. open the blank php file
3. close Atom
4. reopen Atom

**Atom Version:** 1.4.3
**System:** linux 4.2.5-1-ARCH
**Thrown From:** php-integrator-base package, v0.5.1

### Stack Trace

Uncaught No class name passed!

    At /home/username/.atom/packages/php-integrator-base/lib/Proxy.coffee:196

    undefined

### Config
```php
{
  "core": {
    "projectHome": "/mnt/storage/workspace/projects/"
  },
  "php-integrator-base": {}
}
```

### Installed Packages

    # User
    linter, v1.11.3
    linter-php, v1.1.7
    php-integrator-base, v0.5.1
    php-integrator-symbol-viewer, v0.3.2

I also seem to be having a general issue with existing projects: whenever I start typing I get "Indexing failed" message. The code follows the PSR-2 guidelines, sqlite is enables and timezone is set.
<hr>
See the original issue here: https://github.com/Gert-dev/php-integrator-base/issues/82

cc @teresko @woozy

**Comment by 16nsk** [comment]
same here

**Comment by Gert-dev** [comment]
@tocjent This happens when getClassInfo receives `null` for a class name. Adding a check before calling it or catching the error should fix it.
