### ISSUE TITLE
Better focus on the property/method/class

### ISSUE THREAD

**Issue by Arcesilas** [tocjent/php-integrator-symbol-viewer#15]
Hi,

A proposal for a comfort enhancement :)

When clicking on a element in the panel, the cursor is correctly placed, but the scroll is not always very appropriate. If the line is further in the file, the current line is at the bottom of the editor. It would be more relevant if the editor were scrolled so that the current line is at the top.
If it's possible, the top most line should be the first docblock comment of the method /property (if any).

Thanks anyway, I've started using it and it's quite better than the core symbol viewer ;)

**Comment by tocjent** [comment]
Hi! I've published a new version which is basically written from scratch. Scroll should now center around start member line if possible. Feel free to close the issue if this is what you had in mind.

**Comment by Arcesilas** [comment]
Hi! Thanks for your job!

Unfortunately, I have no class, no method, no property displayed. Only the dropdown (empty in most cases), the checkbox for inherited methods and the search field.

![atom-php-integrator-symbol-viewer-empty](https://cloud.githubusercontent.com/assets/5526263/13475843/3e7542d6-e0c5-11e5-8fc5-f0633fc35045.png)

**Comment by tocjent** [comment]
Could you open a new issue and provide more info, i.e. console output and whether other feature of php-integrator-base work?

**Comment by Arcesilas** [comment]
Here it is: #21

**Comment by Arcesilas** [comment]
Ok, now that I realized I forgot about the multiple projects indexing, I can confirm that the focus is much better now!

Thanks a lot!
