### ISSUE TITLE
Distinction between own class and inherited members

### ISSUE THREAD

**Issue by Arcesilas** [tocjent/php-integrator-symbol-viewer#16]
Hi,

Me again :) for another enhancement proposal.

The symbol viewer does not seem to make any distinction between elements declared in the current file and inherited ones. It could be nice and usefull: when you click and later realize you are in another file, you sometimes loose some time trying to understand why the previous method you were in is not here anymore :) (yeah, I should sleep more too, I'd be a bit more aware...)

**Comment by tocjent** [comment]
Thank your very much for your contribution, it means a lot to me. :)

I will try to figure something out over the weekend, since this is something that should be done a long time ago.

**Comment by Arcesilas** [comment]
It's easier to say what can be better (I do it well) than *making* thing actually better (you do it well too)

**Comment by tocjent** [comment]
Similarily to php-integrator-annotations, inherited properties are marked with a link icon since 0.5.1.
