### ISSUE TITLE
Heads up: changes in the next release.

### ISSUE THREAD

**Issue by Gert-dev** [tocjent/php-integrator-symbol-viewer#17]
Hello

Just wanted to give you another heads up about the upcoming version 0.6.0 of the base package. The changes for this upcoming release have somewhat stabilized. (Absolutely no pressure intended.)

For the actual changes you can always take a look at the changelog in the development branch [1]. Don't forget to target service version 0.6.0 in your `package.json` as well.

Thanks for your work!

[1] https://github.com/Gert-dev/php-integrator-base/blob/development/CHANGELOG.md

**Comment by tocjent** [comment]
Adding support for multiple classes in the same file and thus changing determineFullClassName was a gotcha, but I worked it out. Thank you very much for the heads up and for your work!
