### ISSUE TITLE
List is partially hidden when using One dark UI theme with font size >= 12

### ISSUE THREAD

**Issue by ricpelo** [tocjent/php-integrator-symbol-viewer#18]
`Component` class name partially hidden with `font size = 14`:

![2016-02-22-165205_1440x900_scrot](https://cloud.githubusercontent.com/assets/616169/13223481/abcdd688-d984-11e5-8b64-a65f85df52b7.png)

And with `font size = 20` (`Component` class is hidden completely):

![2016-02-22-165147_1440x900_scrot](https://cloud.githubusercontent.com/assets/616169/13223527/d899bd94-d984-11e5-8b8e-b1797ba12057.png)

**Comment by tocjent** [comment]
Hi @ricpelo,

in 0.5.1 the component layout was rewritten to use flexbox, so it should adapt better to font size changes. Could you please check out if those changes fixed the bug?

Thanks,
tocjent

**Comment by ricpelo** [comment]
Great! That's a huge improvement for me. Now it looks much better. Thank you very much! :)
