### ISSUE TITLE
Symbol viewer panel sometimes not showing

### ISSUE THREAD

**Issue by Arcesilas** [tocjent/php-integrator-symbol-viewer#19]
Hi, another problem... :)

For some reason, the symbol viewer is not always displayed. For some files it's here, for others, no.

Something I've noticed: had 5 projects open, viewer not showing. Closed one (a laravel project), viewer showed magically on a file which was already open and which had viewer not displayed

A problem I had not before (but before when or what... ?): in a laravel project, the viewer is no more displayed. At any time. In any file. Never. Ever. That's embarrassing... :/

On small projects (like a new one with 1 or two files...) the viewer is shown.
If a small project is opened while a laravel project is open too, the viewer is not displayed. In any of both projects.
Remove laravel project, index starts (but, I found, very long for just few files) and then viewer is displayed.

When in a Laravel project, the status "Indexind" with progress bar does not appear.

Is there any additionnal information I can provide? How? Is there a console, an error log or somehting like that? (sorry, I'm not familiar with Atom except as a simple end user).
For now, I cannot give any information about how to reproduce this behaviour. If there is a way to get some details about operations beeing done by a package, I could have a look and try to identify the cases the problem happens...

EDIT: I've also noticed that sometimes I need to make a tiny change in the file and save it to have the viewer appear. Forcing index of project is not doing anything.

**Comment by Arcesilas** [comment]
Could it be related to [php-integrator-base issue#81](https://github.com/Gert-dev/php-integrator-base/issues/81) ?

**Comment by Arcesilas** [comment]
And now, I have only one project opened in Atom, with only 1 php file. The viewer panel does not show. Restarting, forcing to re-index do not make it appear. Of course, the key binding does work not either... :/

I really do not understand why sometimes it's displayed and somethimes no.

**Comment by tocjent** [comment]
You're absolutely right, I also noticed that. The problems began after php-integrator-base was pushed to 0.6.0, when multiple classes support was added. I need to investigate this, but I'm a little swamped with my "real" work. so I'm not sure when this will be fixed.

**Comment by Arcesilas** [comment]
Ok, so I'm not drunked (I did not drinked, so...) and it's not Alzheimer (I'm not that old, so...) :)

I guess your real work has some kind of priority in your life ;)
Thanks for your job anyway!

**Comment by tocjent** [comment]
Fixed in 0.5.1.

**Comment by cgardiennet** [comment]
Hi sorry to bother you but for me it's not working anymore.
Here is my config :
* atom 1.6.2
* php-integrator-base 0.8.0

i don't know what kind of information you could need to resolve this issue.
