### ISSUE TITLE
Panel not showing after update => need atom restart

### ISSUE THREAD

**Issue by Arcesilas** [tocjent/php-integrator-symbol-viewer#22]
Not sure it's a bug or not. Just updated the package to 0.5.3 and panel did not open anymore, even after forced reindexing of the project. 

Restarting Atom solved this "problem", which means that it will not happen again... Anyway, it's a little confusing, since I've not seen any package yet that requires Atom restart...

Feel free to close this issue if you think it's not relevant.

Thanks again for your work!

**Comment by tocjent** [comment]
Well, I just tested a fresh installation and it worked just fine, Atom restart was not necessary. Since needing Atom restart is not a big issue in my opinion, I'm going to close this.

Anyway - thank you very much for your help and involvement.

Cheers,
tocjent
