### ISSUE TITLE
Symbols panel not updating after "Close all tabs"

### ISSUE THREAD

**Issue by Arcesilas** [tocjent/php-integrator-symbol-viewer#23]
Hi!

Sorry for reporting another bug: it's a very little bug which is not really inconvenient.

When closing all tabs using "Close all tabs", the panel is still displayed and it still displays the symbols of the last file which was open.
It's really not a big problem, since the editor is not supposed to remain empty for long...
Hiding / Showing the panel does not clean it up.

Opening a PHP file solves the display.

**Comment by Arcesilas** [comment]
Did you really fix this bug in 20 minutes ? :) Rather impressive!
Thanks for your work and your responsiveness!

**Comment by tocjent** [comment]
Well, if the bug is gone then I suppose I did. :) If you would look at the commit it was literally adding one line, and I was doing some github stuff anyway, so why wait? :)

**Comment by tocjent** [comment]
Also: your contributions are very much appreciated, thanks!

**Comment by Arcesilas** [comment]
Yes, it was only one line and git stuff, but still.
The bug is gone, so you actually fixed the bug in 20 minutes :)

My contributions are just bug reporting... I could learn a little more CoffeeScript, EcmaScript and make PRs rather thant just saying "This does not work" or "That does not work either". I always feel sorry when I open the issues page, like I'm just complaining (which I'm not).

Anyway, thanks again!
