### ISSUE TITLE
Option to make it closed by default

### ISSUE THREAD

**Issue by marcoT89** [tocjent/php-integrator-symbol-viewer#28]
Congratulations for the excellent work dude! I would only suggest to create an option in settings (maybe a checkbox) to make it closed by default. In this way i would only open when I want to show it. The way it is, every time i open a new php file class it will open with pane opened by default and i always need to close to get more space in my small monitor. Is that hard to implement?

I'm using atom 1.6 and version 0.5.6 of your package.

Thanks a lot!

**Comment by tocjent** [comment]
Agreed, I also noticed it and it is an annoyance. I will include it in the next release, which would be coming around mid-April.

Thanks for suggestion!

**Comment by marcoT89** [comment]
Thank you! :+1:

**Comment by nahuelhds** [comment]
+1 for this! Nice package guys!

**Comment by tocjent** [comment]
Check out the new 0.6.0 version! I redesigned the hiding/showing (which is now collapsing actually). It is persisted on Atom closing, and should work when switching tabs.
