### ISSUE TITLE
remember when closed in all panes

### ISSUE THREAD

**Issue by g13013** [tocjent/php-integrator-symbol-viewer#29]
Thanks for this package

When I close the viewer and navigate to different files I expect it to be hidden until I open it again, so it would be great to keep the state (open/closed) during the session

**Comment by tocjent** [comment]
Indeed, you're right. that would be fixed in the next release (coming mid-April).

**Comment by tocjent** [comment]
Check out the new 0.6.0 version! I redesigned the hiding/showing (which is now collapsing actually). It is persisted on Atom closing, and should work when switching tabs.

**Comment by Arcesilas** [comment]
Hi,

This bug is still present when splitting panels: switch from left to right (for example) and the panel will show up even if it was hidden before...

**Comment by Arcesilas** [comment]
Some details: this strange behaviour happens when editing files from differents "Project folders".

When editing files in the same project, the panel stays hidden when focusing from one file to another when screen is splitted.
