### ISSUE TITLE
Add this to the list of packages in the base package README?

### ISSUE THREAD

**Issue by Gert-dev** [tocjent/php-integrator-symbol-viewer#3]
Hello

Thanks for taking the time to make a new package using php-integrator and adding more functionality to the PHP chain ;-)! I wanted to let you know that I am open to adding your package to the base package's README along with the other packages for higher visibility for end users. Is this ok or would you prefer me not to give extra exposure to your package yet?

PS: You might already have noticed this, but you can make calls to getClassInfo async by passing true as second parameter, which will allow you to accept a Promise and not hang up Atom whilst the class info is being fetched.

Thanks in advance

**Comment by tocjent** [comment]
Hi!

Thank you very much. I would be honored to have my package in php-integrator-base README, however as you may have noticed the code still requires a few tweaks (i.e. the async class info fetching). Also, I plan on adding a small feature over the weekend. When I'm finished I'll open a PR to the php-integrator-base, ok?

Best regards

**Comment by Gert-dev** [comment]
That sounds good, I'll keep an eye out for your pull request!
