### ISSUE TITLE
Compatible with base 0.8.0?

### ISSUE THREAD

**Issue by ccondrup** [tocjent/php-integrator-symbol-viewer#30]
I recently upgraded gert-dev\php-integrator-base to 0.8.0 (atom prompted me) and can no longer get the symbol panel to show at all.

Is symbol-viewer 0.5.6 compatible with base 0.8.0 and php7x64?
I'm in Atom 1.7.0-dev-829ba67 on Windows 10 x64.
Any debugging procedure I can run to provide more info?

**Comment by tocjent** [comment]
It's not compatible as it is of now, actually. As you can see in package.json:

```

  "consumedServices": {
    "php-integrator.service": {
      "versions": {
        "~0.7.0": "init"
      }
    }
  },
```

I'm afraid I won't be able to fix it until mid-April, which is very unfortunate, since 0.8.0 seems to make some major improvements to the php-integrator ecosystem.

**Comment by Gert-dev** [comment]
Hi @tocjent . I think you can just bump the version to 0.8.0 as I don't think any of the changes actually impact your package. I did a quick test and it seems to be working without any other changes.

**Comment by tocjent** [comment]
Compatible with 0.8.0 in 0.6.0 and as of now with 0.9.0 in 0.6.1, closing
