### ISSUE TITLE
No longer working?

### ISSUE THREAD

**Issue by justbane** [tocjent/php-integrator-symbol-viewer#32]
Looks like this no longer works with new version of php-integrtor?

I don't get any errors but the panel no longer shows up when it should and I can;t seem to launch it or toggle it.

**Comment by nahuelhds** [comment]
+1 Happens here.
When I open the Key Binding Resolver it shows correctly
"atom-workspace": "ctrl-shift-j": "php-integrator-symbol-viewer:toggle-panel"

But nothins happens

**Comment by Arcesilas** [comment]
Hi,

What version of Atom do you have ? Is it up to date ?

**Comment by nahuelhds** [comment]
Latest at the moment 1.7.2

**Comment by tocjent** [comment]
Hey guys, sorry about the development stangation. I forgot to publish the PR by @marcoT89  which fixed php-integrator-base version requirement and it most likely caused the issue. Please update the package to 0.5.8 and let me know if it helped. 

Thank you for involvement.

**Comment by nahuelhds** [comment]
Thanks for the fast solution


Nahuel Sotelo | Desarrollo de soluciones
Acevedo 83, Piso 5, Of. 1 (B1828BPA)
Lomas de Zamora, Buenos Aires, Argentina
(+5411) 5263-0144 | www.cristalmedia.net
<http://www.twitter.com/CristalMedia>
<http://www.linkedin.com/company/cristalmedia>
<http://www.facebook.com/CristalMedia>
<http://plus.google.com/+CristalmediaNet>

2016-04-20 9:41 GMT-03:00 Michał Bobrowicz <notifications@github.com>:
