### ISSUE TITLE
Pane

### ISSUE THREAD

**Issue by adominguez** [tocjent/php-integrator-symbol-viewer#34]
First of all, great work! I love this. One little annoying thing is if I have a PHP file open that have no classes, interfaces or traits I get the side display keeps showing up with the "There is no data to be displayed." even though I hid the right display it keeps popping up as I'm switching through tabs and I have to constantly re-hide it.

**Comment by darkgoldblade01** [comment]
I fixed this in my pull request I just submitted.

Under EmptyFiguresView.js the line `var container = document.createElement('atom-php-integrator-symbol-viewer');` needs to change to `var container = document.createElement('atom-php-integrator-symbol-viewer-content');`

**Comment by tocjent** [comment]
Fixed in 0.6.1
