### ISSUE TITLE
Panel dysfunction with files without classes

### ISSUE THREAD

**Issue by Arcesilas** [tocjent/php-integrator-symbol-viewer#36]
Hi,

So I have all up to date (Atom 1.7.3 and all packages up to date).

When switching to a file with no class, the message "There is no data to be displayed" is displayed. Ok.
When switching back to a file with a class, the message is still present, above the class symbols.
When writing in a file with no symbols, when the panel updates, the message is added. So there can be 256 messages above symbols when switching back to a file with symbols. See capture:

![multiple-messages](https://cloud.githubusercontent.com/assets/5526263/14941978/8f5ca054-0faf-11e6-86b0-2d7931a7146b.png)

**Comment by tocjent** [comment]
This message is useless considering the latest UI changes, the panel should just remain collapsed (until functions are included in the list). I'll remove it in the next release.

**Comment by Arcesilas** [comment]
Thanks for your answer.

I know this message will be removed, but for now, it's very annoying. I've temporarily fixed this by setting `container.innerHTML = "";` in `EmptyFiguresView.js` so that it stops bothering me like this:
![toomaymessages](https://cloud.githubusercontent.com/assets/5526263/14943748/57b0542a-0fe1-11e6-9a58-ceec0a3bd650.png)

:laughing:

**Comment by neolao** [comment]
Same here.

![capture d ecran 2016-05-02 a 10 06 34](https://cloud.githubusercontent.com/assets/149506/14949877/c6ebe824-104d-11e6-9ea6-d515e2a8a5a8.png)

![capture d ecran 2016-05-02 a 10 07 04](https://cloud.githubusercontent.com/assets/149506/14949881/cabfa404-104d-11e6-8214-c7e50a590454.png)

**Comment by darkgoldblade01** [comment]
I fixed this in my pull request I just submitted.

Under EmptyFiguresView.js the line `var container = document.createElement('atom-php-integrator-symbol-viewer');` needs to change to `var container = document.createElement('atom-php-integrator-symbol-viewer-content');`

**Comment by tocjent** [comment]
Fixed in 0.6.1.
