### ISSUE TITLE
Just stopped working in Atom 1.8.0

### ISSUE THREAD

**Issue by nahuelhds** [tocjent/php-integrator-symbol-viewer#42]
I'm a Windows 10 64 bits user.
Atom is 1.8.0
php-integrator-base is 1.0.4

My symbol-viewer version is 0.6.4.

Cannot say what's failing because I cannot even make the panel to show or anything...

Thanks for such a nice plugin!

**Comment by tocjent** [comment]
Hi @nahuelhds,

this is caused by my package requiring php-integrator-base ~0.9.0, since the 1.0 was released recently. I'm going to release changes made by @neolao as soon as possible and the problem should be solved. 
I have to ask you for a bit of patience. :smile: 

Cheers,
tocjent

**Comment by nahuelhds** [comment]
I assumed that it was something like that, just wanted to be sure it was indeed.
Thank you very much @tocjent!
