### ISSUE TITLE
Not working I have all latest versions

### ISSUE THREAD

**Issue by mato777** [tocjent/php-integrator-symbol-viewer#44]
It doesn´t work and does nothing. Any help?

**Comment by wzhangsz** [comment]
me too!

**Comment by eevargas** [comment]
Same here... not working at all after a php-integrator-base update.

**Comment by ricpelo** [comment]
+1

**Comment by m-bobrowicz** [comment]
@mato777 @wzhangsz @eevargas @ricpelo 

I updated project's README with some info about the situation.
