### ISSUE TITLE
side panel not opening

### ISSUE THREAD

**Issue by dimensi** [tocjent/php-integrator-symbol-viewer#46]
I can't open side panel.

**Comment by sajidzaman** [comment]
Same here i am also not able to open the side panel, I tried using Ctrl+Shift+J but failed.

**Comment by hardmagnett** [comment]
+1

**Comment by krewetka** [comment]
+1 , the same here on windows 10 with anniversary update

**Comment by Skullsneeze** [comment]
Same issue on mac El Capitan. Tried altering the keymap as well, but no luck there.

**Comment by bourquem** [comment]
+1 Here. Max OSX El Capitan. I have confirmed that the keymap is being recognized (CTRL-SHIFT-J) and is associated with symbol-viewer, but the panel does not open.

**Comment by dgoosens** [comment]
The reason it it no longer working is indicated in the README:

> symbol-viewer was developed when php-integrator-base was around version 0.7 a few months ago. Due to personal reasons I'm temporarily not able to maintain it and it's not going to work with php-integrator-base >=1.0. If you would like to help with development and publishing of the package please let me know at bobrowicz.michal@gmail.com. Sorry for the inconvenience.

**BUT** am really missing this extension...
Was really helpful...
I hope someone will be able to soon to make it work again.

**Comment by dsturm** [comment]
+1

**Comment by dimensi** [comment]
I close this because it's too old
