### ISSUE TITLE
command to toggle panel's visibility

### ISSUE THREAD

**Issue by tocjent** [tocjent/php-integrator-symbol-viewer#8]

**Comment by Arcesilas** [comment]
:+1: 

Seems a very nice package, we just need to know how to use it. I've tried many possibilities in the command palette, but nothing to display the panel.

**Comment by tocjent** [comment]
Hi!

This is the issue for a feature that is not yet implemented, that is the command is not available right now. If properly installed, the panel should be visible in any PHP file. Here are some ideas what might be wrong:
1) [php-integrator-base](https://github.com/Gert-dev/php-integrator-base) is not installed
2) [php-integrator-base](https://github.com/Gert-dev/php-integrator-base) is not working properly (see FAQ in link)
3) indexing failed and there is no data available (see 2) )

I guess if there are no error notifications one of the clues should help.

Regrards,
tocjent

**Comment by Arcesilas** [comment]
Hi,

Thanks for your answer.
php-integrator base installed and working correctly (the command that checks configuration displays a nice green message).
Using [https://atom.io/packages/symbols-tree-view](Symbols Tree View) for now, it does the job, even if I'd like the display to be a little more configurable (or just more natural: order classes, interfaces, traits, variables, functions,...)

I keep an eye on php-integrator though.

I'd be glad to help by providing some information about configuration, Atom version, debug traces if there are some, etc.

**Comment by Arcesilas** [comment]
No ticket, since I don't know why, default timezone was actually not set (I was sure it was!).
You could, maybe, check for this in the configuration test ?

Works now, but this feature would be great, since one may not always want to have symbols listed (it takes some place too).

Thanks!

Regards

**Comment by tocjent** [comment]
php-integrator-base already has a config check, so I think the ticket belongs there. If I have some free time maybe I'll investigate it there.

Toggling visibility is on the top of my priorities list and will be part of the next release, which will be coming probably at the end of the week.
