### ISSUE TITLE
Heads up: new service version in next release.

### ISSUE THREAD

**Issue by Gert-dev** [tocjent/php-integrator-symbol-viewer#9]
Hello

I wanted to give you a heads up before I release version 0.5.0 of the base package and new versions of the other packages as well. The service version will change to 0.5.0 (so it matches the actual package version) rather than the previous 1.0.0 (I originally thought it best to leave it at 1.0.0 until I released a stable version, that wasn't such a good idea). For your package this should involve nothing more than targeting the new version in your `package.json`, none of the existing service methods should break anything or have changed in major ways.

The release itself will probably follow one of the following days, hopefully even tomorrow, if I encounter no more bugs.

**Comment by tocjent** [comment]
Great, thank you very much for the heads up. I'll try to release an update as soon as possible after 050 comes out.
